# Generated by Django 5.2.7 on 2025-11-04 18:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='worker',
            name='role',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='shift_end',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='shift_start',
        ),
        migrations.AddField(
            model_name='worker',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='worker',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='worker',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='joined_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='worker',
            name='phone',
            field=models.CharField(default=2010, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='worker_type',
            field=models.CharField(choices=[('Plumber', 'Plumber'), ('Electrician', 'Electrician'), ('Carpenter', 'Carpenter'), ('Painter', 'Painter'), ('Helper', 'Helper')], default='plumber', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('payment_status', models.CharField(default='Pending', max_length=20)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('day', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=100)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.worker')),
            ],
        ),
    ]
