# Generated by Django 5.2.8 on 2025-11-12 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_worker_location_worker_role_project_payment_project_and_more'),
    ]

    operations = [
    ]
