# Generated by Django 5.2.8 on 2025-11-14 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0005_worker_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='end_date',
            new_name='completed_date',
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='payment',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='workers.worker'),
        ),
        migrations.AlterField(
            model_name='project',
            name='assigned_workers',
            field=models.ManyToManyField(blank=True, related_name='projects', to='workers.worker'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='workers.worker'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='gender',
            field=models.CharField(blank=True, default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
